# Generated by Django 6.0.4 on 2026-06-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='hash',
            field=models.TextField(unique=True),
        ),
    ]
