# Generated by Django 6.0.4 on 2026-06-01 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='user',
        ),
        migrations.AddField(
            model_name='requests',
            name='user_from',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='requests_as_user_from', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requests',
            name='user_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_as_user_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
