# Generated by Django 6.0.4 on 2026-06-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0002_remove_requests_user_requests_user_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
