# Generated by Django 6.0.4 on 2026-06-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0002_requests_data_alter_lobby_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('playing', 'Playing')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
