# Generated by Django 6.0.4 on 2026-06-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0004_alter_rooms_user_1_in_alter_rooms_user_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='name',
        ),
    ]
