# Generated by Django 6.0.4 on 2026-06-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0005_remove_rooms_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='channel_id',
            field=models.TextField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
