# Generated by Django 6.0.4 on 2026-06-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0006_rooms_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('playing', 'Playing'), ('waiting', 'Waiting'), ('disabled', 'Disabled')], max_length=20),
        ),
    ]
