# Generated by Django 6.0.4 on 2026-06-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0007_alter_rooms_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='info',
            field=models.JSONField(null=True),
        ),
    ]
